#Pat Kolakowski, pkolak3@uic.edu
#Project 1: Power and the Passion
#CS 424, Spring 202
#Data sourced from: https://www.eia.gov/electricity/data/state/

#libraries to include
library(shiny)
library(shinydashboard)
library(ggplot2)
library(lubridate)
library(stringr)
library(DT)
library(jpeg)
library(grid)
library(usmap)
library(leaflet)
library(scales)


data <- read.csv("annual_generation_state.csv", header = TRUE, stringsAsFactors = FALSE) #Read in data
data$GENERATION..Megawatthours. <- as.numeric(gsub(',', '', data$GENERATION..Megawatthours.)) #Remove commas from generation data
colnames(data) <- c("YEAR", "STATE", "TYPE.OF.PRODUCER", "ENERGY.SOURCE", "GENERATION") #Rename columns

#Format columns and data
data <- data[data$GENERATION >= 0,]
data <- data[!data$STATE=="  ",]
data$STATE <- toupper(data$STATE)
data$STATE = as.factor(data$STATE)
data$TYPE.OF.PRODUCER = as.factor(data$TYPE.OF.PRODUCER)
data$ENERGY.SOURCE = as.factor(data$ENERGY.SOURCE)
data <- data[data$ENERGY.SOURCE != "Other",]
data <- data[data$ENERGY.SOURCE != "Other Gases",]
data <- data[data$ENERGY.SOURCE != "Other Biomass",]
data <- data[data$ENERGY.SOURCE != "Pumped Storage",]
levels(data$ENERGY.SOURCE)[levels(data$ENERGY.SOURCE) == "Hydroelectric Conventional"] <- "Hydro"
levels(data$ENERGY.SOURCE)[levels(data$ENERGY.SOURCE) == "Solar Thermal and Photovoltaic"] <- "Solar"
levels(data$ENERGY.SOURCE)[levels(data$ENERGY.SOURCE) == "Wood and Wood Derived Fuels"] <- "Wood"
usdata <- data[data$STATE == "US-TOTAL" & data$ENERGY.SOURCE != "Total" & data$TYPE.OF.PRODUCER != "Total Electric Power Industry",]


#Color palettes corresponding to each energy source
colors <- c("#f8766d", "#d39200", "#93aa00", "#00ba38", "#02c19e", "#00b9e3", "#619bff", "#db72fb", "#ff61c3")
names(colors) = c("Coal", "Geothermal", "Hydro", "Natural Gas", "Nuclear", "Petroleum", "Solar", "Wind", "Wood")
colorswtotal <- c("#f8766d", "#d39200", "#93aa00", "#00ba38", "#02c19e", "#00b9e3", "#619bff", "#db72fb", "#ff61c3", "#000000")
names(colorswtotal) = c("Coal", "Geothermal", "Hydro", "Natural Gas", "Nuclear", "Petroleum", "Solar", "Wind", "Wood", "Total")


#Used during filtered plot creation
'%notin%' <- Negate('%in%')



ui <- dashboardPage(
    dashboardHeader(title = "CS 424: Project 1\n"),
    dashboardSidebar(disable = FALSE, collapsed = FALSE,
                    sidebarMenu(
                        id = "tab",
                        menuItem("US Overview", tabName = "1"),
                        menuItem("State Graphs", tabName = "2"),
                        menuItem("US Heatmaps", tabName = "3"),
                        menuItem("About", tabName = "4")
                    ),
                    uiOutput("tabMenu")
                    ),
dashboardBody(
    tabItems(
        tabItem(tabName = "1", #Homepage
          fluidRow(
            column(4,
                fluidRow(
                  box(title = "Energy generated by source per year from 1990-2019", solidHeader = TRUE, status = "primary", width = 12,
                      plotOutput("generatedBar")
                  )
                 ),
                fluidRow(
                  box(title = "Percent of total production for each energy source from 1990-2019", solidHeader = TRUE, status = "primary", width = 12,
                      plotOutput("generatedPercentBar", height = 400)
                  )
                )
            ),
            column(4,
               fluidRow(
                    box(title = "Energy generated by source per year from 1990-2019", solidHeader = TRUE, status = "primary", width = 12,
                        plotOutput("generatedLine", height = 400)
                    )
                ),
               fluidRow(
                    box(title = "Percent of total production for each energy source from 1990-2019", solidHeader = TRUE, status = "primary", width = 12,
                        plotOutput("generatedPercentLine", height = 400)
                    )
                )
            ),
           column(4,
               fluidRow(
                    box( title = "Energy generated by source per year from 1990-2019", solidHeader = TRUE, status = "primary", width = 12,
                        dataTableOutput("generatedTable"), style = "height:420px; overflow-y: scroll;overflow-x: scroll;"
                    )
                ),
               fluidRow(
                    box( title = "Percent of total production for each energy source from 1990-2019", solidHeader = TRUE, status = "primary", width = 12,
                        dataTableOutput("generatedPercentTable"), style = "height:420px; overflow-y: scroll;overflow-x: scroll;"
                    )
                   )
                )
                )
               ),

    tabItem(tabName = "2", #State Graphs
        fluidRow(
            column(6, align = "center",
                h4("State 1")
            ),
            column(6, align = "center",
                h4("State 2")
            )
        ),
        fluidRow(
            column(3,
                fluidRow(
                  box(title = "Energy generated by source", solidHeader = TRUE, status = "primary", width = 12,
                      plotOutput("generatedBar1")
                  )
                 ),
                fluidRow(
                  box(title = "Percent of total production", solidHeader = TRUE, status = "primary", width = 12,
                    plotOutput("generatedPercentBar1", height = 400)
                  )
                )
            ),
            column(3,
                fluidRow(
                  box(title = "Energy generated by source", solidHeader = TRUE, status = "primary", width = 12,
                    plotOutput("generatedLine1")
                  )
                 ),
                fluidRow(
                  box(title = "Percent of total production", solidHeader = TRUE, status = "primary", width = 12,
                    plotOutput("generatedPercentLine1", height = 400)
                  )
                )
            ),
            column(3,
            fluidRow(
              box(title = "Energy generated by source", solidHeader = TRUE, status = "primary", width = 12,
                plotOutput("generatedBar2")
              )
             ),
            fluidRow(
              box(title = "Percent of total production", solidHeader = TRUE, status = "primary", width = 12,
                plotOutput("generatedPercentBar2", height = 400)
              )
            )
            ),
            column(3,
               fluidRow(
                    box(title = "Energy generated by source", solidHeader = TRUE, status = "primary", width = 12,
                        plotOutput("generatedLine2")
                    )
                ),
               fluidRow(
                    box(title = "Percent of total production", solidHeader = TRUE, status = "primary", width = 12,
                     plotOutput("generatedPercentLine2", height = 400)
                    )
                )
            )
            )
           ),
    tabItem(tabName = "3", #US Heatmaps
        fluidRow(
            column(6, align = "center",
                h4("Filter 1")
            ),
            column(6, align = "center",
                h4("Filter 2")
            )
        ),
        fluidRow(
            column(6,
                fluidRow(
                  box(title = "Energy generated by state", solidHeader = TRUE, status = "primary", width = 12,
                        plotOutput("plotMap1")
                    )
                 )
            ),
            column(6,
               fluidRow(
                    box(title = "Energy generated by state", solidHeader = TRUE, status = "primary", width = 12,
                        plotOutput("plotMap2")
                    )
                )
            )
        ),
        fluidRow(
            column(6,
                fluidRow(
                  box(title = "Percent of energy generated by state", solidHeader = TRUE, status = "primary", width = 12,
                        plotOutput("plotPercentMap1")
                    )
                 )
            ),
            column(6,
               fluidRow(
                    box(title = "Percent of energy generated by state", solidHeader = TRUE, status = "primary", width = 12,
                       plotOutput("plotPercentMap2")
                    )
                )
            )
        )
       ),
    tabItem(tabName = "4", #About page
        h3("Project 1: Power and the Passion"),
        h4("by Pat Kolakowski (pkolak3@uic.edu)"),
        h4("for UIC CS 424, Spring 2020"),
        h4("Data sourced from https://www.eia.gov/electricity/data/state/")
        )
    )
)
)


server <- function(input, output, session) {    
    updateSelectizeInput(session, 'stateSelect', choices = data$STATE, server = TRUE)
    updateSelectizeInput(session, 'energySelect', choices = data$ENERGY.SOURCE, server = TRUE)
    updateSelectizeInput(session, 'yearSelect', choices = data$YEAR, server = TRUE)

    years = seq(1990, 2019, 1)

    output$tabMenu <- renderUI({ #Render UI based on tab selected
        
        #Page 1, show overview of the US
        if(input$tab == "1") {
            dyn_ui <- checkboxGroupInput("checkGroup", label = h4("Energy Sources"), #Checkbox with energy source options
                        choices = list(
                            "All" = "All",
                            "Coal" = "Coal",
                            "Geothermal" = "Geothermal",
                            "Hydro" = "Hydro",
                              "Natural Gas" = "Natural Gas",
                            "Nuclear" = "Nuclear",
                            "Petroleum" = "Petroleum",
                            "Solar" = "Solar",
                            "Wind" = "Wind",
                            "Wood" = "Wood"),
                        selected = "All")
        }

        #Page 2, compare graphs
        if(input$tab == "2") {
            dyn_ui <- list(
                    h4("State 1"), #State 1 filter drop down menu
                    selectInput("stateSelect1", label = h5("State"), choices = NULL),
                    selectInput("energySelect1", label = h5("Energy Source"), choices = NULL),
                    selectInput("yearSelect1", label = h5("Year"), choices = NULL),
                    h4("State 2"), #State 2 filter drop down menu
                    selectInput("stateSelect2", label = h5("State"), choices = NULL),
                    selectInput("energySelect2", label = h5("Energy Source"), choices = NULL),
                    selectInput("yearSelect2", label = h5("Year"), choices = NULL)
                    )
                    
                    fullStateName <- state.name[match(data$STATE,state.abb)]
                    fullStateName <- c("Total US", fullStateName, "Washington DC")
                    
                    #Update state 1 and 2 drop down menu later on for faster runtimes
                    updateSelectizeInput(session, 'stateSelect1', choices = fullStateName, selected = "Total US", server = TRUE)
                    updateSelectizeInput(session, 'energySelect1', choices = data$ENERGY.SOURCE, selected = "Total", server = TRUE)
                    updateSelectizeInput(session, 'yearSelect1', choices = c("All", years), selected = "All", server = TRUE)
                    updateSelectizeInput(session, 'stateSelect2', choices = fullStateName, selected = "Illinois", server = TRUE)
                    updateSelectizeInput(session, 'energySelect2', choices = data$ENERGY.SOURCE, selected = "Total",  server = TRUE)
                    updateSelectizeInput(session, 'yearSelect2', choices = c("All", years), selected = "All", server = TRUE)
        }
        
        #Page 3, compare heatmaps
        if(input$tab == "3") {
            dyn_ui <- list(
                    h4("Filter 1"), #Heatmap 1 filter drop down menu
                    selectInput("energySelect1", label = h5("Energy Source"), choices = NULL),
                    selectInput("yearSelect1", label = h5("Year"), choices = NULL),
                    h4("Filter 2"), #Heatmap 2 filter drop down menu
                    selectInput("energySelect2", label = h5("Energy Source"), choices = NULL),
                    selectInput("yearSelect2", label = h5("Year"), choices = NULL)
                    )
                    
                    #Update heatmap 1 and 2 drop down menu later on for faster runtimes
                    updateSelectizeInput(session, 'energySelect1', choices = data$ENERGY.SOURCE, selected = "Total", server = TRUE)
                    updateSelectizeInput(session, 'yearSelect1', choices = c("All", years), selected = "All", server = TRUE)
                    updateSelectizeInput(session, 'energySelect2', choices = data$ENERGY.SOURCE, selected = "Coal",  server = TRUE)
                    updateSelectizeInput(session, 'yearSelect2', choices = c("All", years), selected = "All", server = TRUE)
        }
        
        #Page 4, about menu
        if(input$tab == "4") {
            dyn_ui <- list()
        }
        return(dyn_ui) #Update UI corresponding to tab selected
    })

    #Used to plot map of total US production
    output$plotMap1 <- renderPlot({
        #Format data into matrix
        mapdata <- as.data.frame.matrix(data)
        mapdata <- mapdata[mapdata$STATE != "DC",]
        mapdata$ENERGY.SOURCE <- as.character(mapdata$ENERGY.SOURCE)
        mapdata$STATE <- as.character(mapdata$STATE)
        mapdata$TYPE.OF.PRODUCER <- as.character(mapdata$TYPE.OF.PRODUCER)
        
        #Find color corresponding to energy source selected
        mapcolor <- colorswtotal[input$energySelect1]
        colorval <- cbind(read.table(text = names(mapcolor)), mapcolor)
        
        #Format column titles for plot_usmap
        colnames(mapdata) <- c("YEAR", "state", "TYPE.OF.PRODUCER", "ENERGY.SOURCE", "GENERATION")
        
        map <- plot_usmap(regions = "state") #Default map, updated based on criteia selected
        
        if("All" %notin% input$yearSelect1 && "Total" %notin% input$energySelect1) { #Filter by year and energy source
            map <-
            plot_usmap(data=subset(mapdata, ENERGY.SOURCE %in% input$energySelect1 & YEAR %in% input$yearSelect1), values = "GENERATION") +
            scale_fill_continuous(low = "white", high = colorval$mapcolor, name = "Energy Generated (MWh)",labels = unit_format(unit = "M", scale = 1e-6)) +
            theme(legend.position = "right")
        } else if("All" %notin% input$yearSelect1) { #Filter by year
            map <-
            plot_usmap(data=subset(mapdata, ENERGY.SOURCE != "Total" & YEAR %in% input$yearSelect1), values = "GENERATION") +
            scale_fill_continuous(low = "white", high = colorval$mapcolor, name = "Energy Generated (MWh)",labels = unit_format(unit = "M", scale = 1e-6)) +
            theme(legend.position = "right")
        } else if("Total" %notin% input$enerySelect1) { #Filter by energy source
            map <-
            plot_usmap(data=subset(mapdata, ENERGY.SOURCE %in% input$energySelect1), values = "GENERATION") +
            scale_fill_continuous(low = "white", high = colorval$mapcolor, name = "Energy Generated (MWh)",labels = unit_format(unit = "M", scale = 1e-6)) +
            theme(legend.position = "right")
        } else { #Default, total
            map <-
            plot_usmap(data=mapdata, values = "GENERATION") +
            scale_fill_continuous(low = "white", high ="black", name = "Energy Generated (MWh)",labels = unit_format(unit = "M", scale = 1e-6)) +
            theme(legend.position = "right")
        }
        map
    })
    
    
    #Used to plot heatmap of total US production
    output$plotMap2 <- renderPlot({
        #Format data into matrix
        mapdata <- as.data.frame.matrix(data)
        mapdata <- mapdata[mapdata$STATE != "DC",]
        mapdata$ENERGY.SOURCE <- as.character(mapdata$ENERGY.SOURCE)
        mapdata$STATE <- as.character(mapdata$STATE)
        mapdata$TYPE.OF.PRODUCER <- as.character(mapdata$TYPE.OF.PRODUCER)
        
        #Find color corresponding to energy source selected
        mapcolor <- colorswtotal[input$energySelect2]
        colorval <- cbind(read.table(text = names(mapcolor)), mapcolor)

        #Format column titles for plot_usmap
        colnames(mapdata) <- c("YEAR", "state", "TYPE.OF.PRODUCER", "ENERGY.SOURCE", "GENERATION")
        
        map <- plot_usmap(regions = "state") #Default map, updated based on criteia selected
        
        if("All" %notin% input$yearSelect2 && "Total" %notin% input$energySelect2) { #Filter by year and energy source
            map <-
            plot_usmap(data=subset(mapdata, ENERGY.SOURCE %in% input$energySelect2 & YEAR %in% input$yearSelect2), values = "GENERATION") +
            scale_fill_continuous(low = "white", high = colorval$mapcolor, name = "Energy Generated (MWh)",labels = unit_format(unit = "M", scale = 1e-6)) +
            theme(legend.position = "right")
        } else if("All" %notin% input$yearSelect2) { #Filter by year
            map <-
            plot_usmap(data=subset(mapdata, ENERGY.SOURCE != "Total" & YEAR %in% input$yearSelect2), values = "GENERATION") +
            scale_fill_continuous(low = "white", high = colorval$mapcolor, name = "Energy Generated (MWh)",labels = unit_format(unit = "M", scale = 1e-6)) +
            theme(legend.position = "right")
        } else if("Total" %notin% input$enerySelect2) { #Filter by energy source
            map <-
            plot_usmap(data=subset(mapdata, ENERGY.SOURCE %in% input$energySelect2), values = "GENERATION") +
            scale_fill_continuous(low = "white", high = colorval$mapcolor, name = "Energy Generated (MWh)",labels = unit_format(unit = "M", scale = 1e-6)) +
            theme(legend.position = "right")
        } else { #Default, total
            map <-
            plot_usmap(data=mapdata, values = "GENERATION") +
            scale_fill_continuous(low = "white", high ="black", name = "Energy Generated (MWh)",labels = unit_format(unit = "M", scale = 1e-6)) +
            theme(legend.position = "right")
        }
        map

    })
    
    #Used to plot heatmap of total US production by percent
    output$plotPercentMap1 <- renderPlot({
        #Format data into matrix
        mapdata <- as.data.frame.matrix(data)
        mapdata <- mapdata[mapdata$STATE != "DC",]
        mapdata$ENERGY.SOURCE <- as.character(mapdata$ENERGY.SOURCE)
        mapdata$STATE <- as.character(mapdata$STATE)
        mapdata$TYPE.OF.PRODUCER <- as.character(mapdata$TYPE.OF.PRODUCER)
        
        #Find color corresponding to energy source selected
        mapcolor <- colorswtotal[input$energySelect1]
        colorval <- cbind(read.table(text = names(mapcolor)), mapcolor)
                
        #Calculate percent of energy source production by total US production
        percent <- transform(mapdata, PERCENT.OF.TOTAL = ave(GENERATION, YEAR, FUN = function(x) paste0(round(x/sum(x), 4) * 100), "%"))
        percent$PERCENT.OF.TOTAL <- as.numeric(as.character(percent$PERCENT.OF.TOTAL))
        
        #Format column titles for plot_usmap
        colnames(percent) <- c("YEAR", "state", "TYPE.OF.PRODUCER", "ENERGY.SOURCE", "GENERATION", "PERCENT.OF.TOTAL")
        
        map <- plot_usmap(regions = "state") #Default map, updated based on criteia selected
        
        if("All" %notin% input$yearSelect1 && "Total" %notin% input$energySelect1) { #Filter by year and energy source
            map <-
            plot_usmap(data=subset(percent, ENERGY.SOURCE %in% input$energySelect1 & YEAR %in% input$yearSelect1), values = "PERCENT.OF.TOTAL") +
            scale_fill_continuous(low = "white", high = colorval$mapcolor, name = "Percent of total", labels = scales::percent) +
            theme(legend.position = "right")
        } else if("All" %notin% input$yearSelect1) { #Filter by year
            map <-
            plot_usmap(data=subset(percent, ENERGY.SOURCE != "Total" & YEAR %in% input$yearSelect1), values = "PERCENT.OF.TOTAL") +
            scale_fill_continuous(low = "white", high = colorval$mapcolor, name = "Percent of total", labels = scales::percent) +
            theme(legend.position = "right")
        } else if("Total" %notin% input$enerySelect1) { #Filter by energy source
            map <-
            plot_usmap(data=subset(percent, ENERGY.SOURCE %in% input$energySelect1), values = "PERCENT.OF.TOTAL") +
            scale_fill_continuous(low = "white", high = colorval$mapcolor, name = "Percent of total", labels = scales::percent) +
            theme(legend.position = "right")
        } else { #Default, total
            map <-
            plot_usmap(data=percent, values = "PERCENT.OF.TOTAL") +
            scale_fill_continuous(low = "white", high ="black", name = "Percent of total", labels = scales::percent) +
            theme(legend.position = "right")
        }
        map
    })
    
    #Used to plot heatmap of total US production by percent
    output$plotPercentMap2 <- renderPlot({
        #Format data into matrix
        mapdata <- as.data.frame.matrix(data)
        mapdata <- mapdata[mapdata$STATE != "DC",]
        mapdata$ENERGY.SOURCE <- as.character(mapdata$ENERGY.SOURCE)
        mapdata$STATE <- as.character(mapdata$STATE)
        mapdata$TYPE.OF.PRODUCER <- as.character(mapdata$TYPE.OF.PRODUCER)
        
        #Find color corresponding to energy source selected
        mapcolor <- colorswtotal[input$energySelect2]
        colorval <- cbind(read.table(text = names(mapcolor)), mapcolor)
                
        #Calculate percent of energy source production by total US production
        percent <- transform(mapdata, PERCENT.OF.TOTAL = ave(GENERATION, YEAR, FUN = function(x) paste0(round(x/sum(x), 4) * 100), "%"))
        percent$PERCENT.OF.TOTAL <- as.numeric(as.character(percent$PERCENT.OF.TOTAL))
        
        #Format column titles for plot_usmap
        colnames(percent) <- c("YEAR", "state", "TYPE.OF.PRODUCER", "ENERGY.SOURCE", "GENERATION", "PERCENT.OF.TOTAL")
        
        map <- plot_usmap(regions = "state") #Default map, updated based on criteia selected
        
        if("All" %notin% input$yearSelect2 && "Total" %notin% input$energySelect2) { #Filter by year and energy source
            map <-
            plot_usmap(data=subset(percent, ENERGY.SOURCE %in% input$energySelect2 & YEAR %in% input$yearSelect2), values = "PERCENT.OF.TOTAL") +
            scale_fill_continuous(low = "white", high = colorval$mapcolor, name = "Percent of total", labels = scales::percent) +
            theme(legend.position = "right")
        } else if("All" %notin% input$yearSelect2) { #Filter by year
            map <-
            plot_usmap(data=subset(percent, ENERGY.SOURCE != "Total" & YEAR %in% input$yearSelect2), values = "PERCENT.OF.TOTAL") +
            scale_fill_continuous(low = "white", high = colorval$mapcolor, name = "Percent of total", labels = scales::percent) +
            theme(legend.position = "right")
        } else if("Total" %notin% input$enerySelect2) { #Filter by energy source
            map <-
            plot_usmap(data=subset(percent, ENERGY.SOURCE %in% input$energySelect2), values = "PERCENT.OF.TOTAL") +
            scale_fill_continuous(low = "white", high = colorval$mapcolor, name = "Percent of total", labels = scales::percent) +
            theme(legend.position = "right")
        } else { #Default, total
            map <-
            plot_usmap(data=percent, values = "PERCENT.OF.TOTAL") +
            scale_fill_continuous(low = "white", high ="black", name = "Percent of total", labels = scales::percent) +
            theme(legend.position = "right")
        }
        map

    })

    #Used to generate stacked bar chart of total US data
    output$generatedBar <- renderPlot({      
        value <- cat(input$checkGroup)
        
        if("All" %in% input$checkGroup) { #Show all energy sources
            graph <-
            ggplot(usdata, aes(x = YEAR, y = GENERATION, fill = ENERGY.SOURCE)) +
            stat_summary(fun.y = sum, geom = "bar", position = "stack") + 
            scale_y_continuous(labels = unit_format(unit = "B", scale = 1e-9)) + 
            labs(fill = "Sources") + 
            xlab("Year") + 
            ylab("Energy Generated (MWh)") +
            scale_fill_manual(values = colors)
        } else { #Filter by energy source selected
            graph <-
            ggplot(subset(usdata, ENERGY.SOURCE %in% input$checkGroup), aes(x = YEAR, y = GENERATION, fill = ENERGY.SOURCE)) +
            stat_summary(fun.y = sum, geom = "bar", position = "stack") + 
            scale_y_continuous(labels = unit_format(unit = "B", scale = 1e-9)) + 
            labs(fill = "Energy Sources") + 
            xlab("Year") + 
            ylab("Energy Generated (MWh)") +
            scale_fill_manual(values = colors)
        }
      
        graph
            
     })

    #Used to generate stacked bar chart of total US and individual state data
     output$generatedBar1 <- renderPlot({
        value <- cat(input$stateSelect1)
                
        #Convert full state name back to abbreviation
        if("Total US" %in% input$stateSelect1) {
            stateSelected <- "US-TOTAL"
        } else if("Washington DC" %in% input$stateSelect1) {
            stateSelected <- "DC"
        } else {
            stateSelected <- state.abb[match(input$stateSelect1,state.name)]
        }
        
        if("All" %notin% input$yearSelect1 && "Total" %notin% input$energySelect1) { #Filter by year and energy source
            graph <-
            ggplot(subset(data, ENERGY.SOURCE %in% input$energySelect1 & STATE %in% stateSelected & YEAR %in% input$yearSelect1), aes(x = YEAR, y = GENERATION, fill = ENERGY.SOURCE)) +
            stat_summary(fun.y = sum, geom = "bar", position = "stack") +
            scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6)) +
            labs(fill = "Sources") +
            xlab("Year") +
            ylab("Energy Generated (MWh)") +
            scale_fill_manual(values = colors)
        } else if("All" %notin% input$yearSelect1) { #Filter by year
            graph <-
            ggplot(subset(data, ENERGY.SOURCE != "Total" & STATE %in% stateSelected & YEAR %in% input$yearSelect1), aes(x = YEAR, y = GENERATION, fill = ENERGY.SOURCE)) +
            stat_summary(fun.y = sum, geom = "bar", position = "stack") +
            scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6)) +
            labs(fill = "Sources") +
            xlab("Year") +
            ylab("Energy Generated (MWh)") +
            scale_fill_manual(values = colors)
        }  else if("Total" %notin% input$energySelect1) { #Filter by energy source
            graph <-
            ggplot(subset(data, ENERGY.SOURCE %in% input$energySelect1 & STATE %in% stateSelected), aes(x = YEAR, y = GENERATION, fill = ENERGY.SOURCE)) +
            stat_summary(fun.y = sum, geom = "bar", position = "stack") +
            scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6)) +
            labs(fill = "Sources") +
            xlab("Year") +
            ylab("Energy Generated (MWh)") +
            scale_fill_manual(values = colors)
        } else if("US-TOTAL" %notin% stateSelected) { #Filter by state
            graph <-
            ggplot(subset(data, ENERGY.SOURCE != "Total" & STATE %in% stateSelected), aes(x = YEAR, y = GENERATION, fill = ENERGY.SOURCE)) +
            stat_summary(fun.y = sum, geom = "bar", position = "stack") +
            scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6)) +
            labs(fill = "Sources") +
            xlab("Year") +
            ylab("Energy Generated (MWh)") +
            scale_fill_manual(values = colors)
        } else { #Default, total for state selected
            graph <-
            ggplot(subset(data, ENERGY.SOURCE != "Total" & STATE %in% stateSelected), aes(x = YEAR, y = GENERATION, fill = ENERGY.SOURCE)) +
            stat_summary(fun.y = sum, geom = "bar", position = "stack") +
            scale_y_continuous(labels = unit_format(unit = "B", scale = 1e-9)) +
            labs(fill = "Sources") +
            xlab("Year") +
            ylab("Energy Generated (MWh)") +
            scale_fill_manual(values = colors)
        }
      
        graph
     })

     #Used to generate stacked bar chart of total US and individual state data
     output$generatedBar2 <- renderPlot({      
        value <- cat(input$stateSelect2)
        
        #Convert full state name back to abbreviation
        if("Total US" %in% input$stateSelect2) {
            stateSelected <- "US-TOTAL"
        } else if("Washington DC" %in% input$stateSelect2) {
            stateSelected <- "DC"
        } else {
            stateSelected <- state.abb[match(input$stateSelect2,state.name)]
        }
        
        if("All" %notin% input$yearSelect2 && "Total" %notin% input$energySelect2) { #Filter by year and energy source
            graph <-
            ggplot(subset(data, ENERGY.SOURCE %in% input$energySelect2 & STATE %in% stateSelected & YEAR %in% input$yearSelect2), aes(x = YEAR, y = GENERATION, fill = ENERGY.SOURCE)) +
            stat_summary(fun.y = sum, geom = "bar", position = "stack") +
            scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6)) +
            labs(fill = "Sources") +
            xlab("Year") +
            ylab("Energy Generated (MWh)") +
            scale_fill_manual(values = colors)
        } else if("All" %notin% input$yearSelect2) { #Filter by year
            graph <-
            ggplot(subset(data, ENERGY.SOURCE != "Total" & STATE %in% stateSelected & YEAR %in% input$yearSelect2), aes(x = YEAR, y = GENERATION, fill = ENERGY.SOURCE)) +
            stat_summary(fun.y = sum, geom = "bar", position = "stack") +
            scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6)) +
            labs(fill = "Sources") +
            xlab("Year") +
            ylab("Energy Generated (MWh)") +
            scale_fill_manual(values = colors)
        }  else if("Total" %notin% input$energySelect2) { #Filter by energy source
            graph <-
            ggplot(subset(data, ENERGY.SOURCE %in% input$energySelect2 & STATE %in% stateSelected), aes(x = YEAR, y = GENERATION, fill = ENERGY.SOURCE)) +
            stat_summary(fun.y = sum, geom = "bar", position = "stack") +
            scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6)) +
            labs(fill = "Sources") +
            xlab("Year") +
            ylab("Energy Generated (MWh)") +
            scale_fill_manual(values = colors)
        } else if("US-TOTAL" %notin% stateSelected) { #Filter by state
            graph <-
            ggplot(subset(data, ENERGY.SOURCE != "Total" & STATE %in% stateSelected), aes(x = YEAR, y = GENERATION, fill = ENERGY.SOURCE)) +
            stat_summary(fun.y = sum, geom = "bar", position = "stack") +
            scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6)) +
            labs(fill = "Sources") +
            xlab("Year") +
            ylab("Energy Generated (MWh)") +
            scale_fill_manual(values = colors)
        } else { #Default, total for state selected
            graph <-
            ggplot(subset(data, ENERGY.SOURCE != "Total" & STATE %in% stateSelected), aes(x = YEAR, y = GENERATION, fill = ENERGY.SOURCE)) +
            stat_summary(fun.y = sum, geom = "bar", position = "stack") +
            scale_y_continuous(labels = unit_format(unit = "B", scale = 1e-9)) +
            labs(fill = "Sources") +
            xlab("Year") +
            ylab("Energy Generated (MWh)") +
            scale_fill_manual(values = colors)
        }
        graph
     })

    #Used to generate stacked bar chart of total US production by percent
    output$generatedPercentBar <- renderPlot({
        value <- cat(input$checkGroup)
        
        if("All" %in% input$checkGroup) { #Show all energy sources
            graph <-
            ggplot(usdata, aes(x = YEAR, y = GENERATION, fill = ENERGY.SOURCE)) +
            geom_bar(position = "fill", stat = "identity") + 
            scale_y_continuous(labels = scales::percent) + 
            labs(fill = "Energy Sources") + 
            xlab("Year") + 
            ylab("Percent of total") +
            scale_fill_manual(values = colors)
        } else { #Filter by energy source selected
            graph <- 
            ggplot(subset(usdata, ENERGY.SOURCE %in% input$checkGroup), aes(x = YEAR, y = GENERATION, fill = ENERGY.SOURCE)) +
            geom_bar(position = "fill", stat = "identity") + 
            scale_y_continuous(labels = scales::percent) + 
            labs(fill = "Energy Sources") + 
            xlab("Year") + 
            ylab("Percent of total") +
            scale_fill_manual(values = colors)
        }
            graph
        })
    
    #Used to generate stacked bar chart of total US and individual state data by percent
    output$generatedPercentBar1 <- renderPlot({
        value <- cat(input$stateSelect1)
        
        #Convert full state name back to abbreviation
        if("Total US" %in% input$stateSelect1) {
            stateSelected <- "US-TOTAL"
        } else if("Washington DC" %in% input$stateSelect1) {
            stateSelected <- "DC"
        } else {
            stateSelected <- state.abb[match(input$stateSelect1,state.name)]
        }
        
        if("All" %notin% input$yearSelect1 && "Total" %notin% input$energySelect1) { #Filter by year and energy source
            graph <-
            ggplot(subset(data, ENERGY.SOURCE %in% input$energySelect1 & STATE %in% stateSelected & YEAR %in% input$yearSelect1), aes(x = YEAR, y = GENERATION, fill = ENERGY.SOURCE)) +
            geom_bar(position = "fill", stat = "identity") +
            scale_y_continuous(labels = scales::percent) +
            labs(fill = "Sources") +
            xlab("Year") +
            ylab("Percent of total") +
            scale_fill_manual(values = colors)
        } else if("All" %notin% input$yearSelect1) { #Filter by year
            graph <-
            ggplot(subset(data, ENERGY.SOURCE != "Total" & STATE %in% stateSelected & YEAR %in% input$yearSelect1), aes(x = YEAR, y = GENERATION, fill = ENERGY.SOURCE)) +
            geom_bar(position = "fill", stat = "identity") +
            scale_y_continuous(labels = scales::percent) +
            labs(fill = "Sources") +
            xlab("Year") +
            ylab("Percent of total") +
            scale_fill_manual(values = colors)
        }  else if("Total" %notin% input$energySelect1) { #Filter by energy source
            graph <-
            ggplot(subset(data, ENERGY.SOURCE %in% input$energySelect1 & STATE %in% stateSelected), aes(x = YEAR, y = GENERATION, fill = ENERGY.SOURCE)) +
            geom_bar(position = "fill", stat = "identity") +
            scale_y_continuous(labels = scales::percent) +
            labs(fill = "Sources") +
            xlab("Year") +
            ylab("Percent of total") +
            scale_fill_manual(values = colors)
        } else if("US-TOTAL" %notin% stateSelected) { #Filter by state
            graph <-
            ggplot(subset(data, ENERGY.SOURCE != "Total" & STATE %in% stateSelected), aes(x = YEAR, y = GENERATION, fill = ENERGY.SOURCE)) +
            geom_bar(position = "fill", stat = "identity") +
            scale_y_continuous(labels = scales::percent) +
            labs(fill = "Sources") +
            xlab("Year") +
            ylab("Percent of total") +
            scale_fill_manual(values = colors)
        } else { #Default, total for state selected
            graph <-
            ggplot(subset(data, ENERGY.SOURCE != "Total" & STATE %in% stateSelected), aes(x = YEAR, y = GENERATION, fill = ENERGY.SOURCE)) +
            geom_bar(position = "fill", stat = "identity") +
            scale_y_continuous(labels = scales::percent) +
            labs(fill = "Sources") +
            xlab("Year") +
            ylab("Percent of total") +
            scale_fill_manual(values = colors)
        }
        graph
    })
    
    #Used to generate stacked bar chart of total US and individual state data by percent
    output$generatedPercentBar2 <- renderPlot({
        value <- cat(input$stateSelect2)
        
        #Convert full state name back to abbreviation
        if("Total US" %in% input$stateSelect2) {
            stateSelected <- "US-TOTAL"
        } else if("Washington DC" %in% input$stateSelect2) {
            stateSelected <- "DC"
        } else {
            stateSelected <- state.abb[match(input$stateSelect2,state.name)]
        }
        
        if("All" %notin% input$yearSelect2 && "Total" %notin% input$energySelect2) { #Filter by year and energy source
            graph <-
            ggplot(subset(data, ENERGY.SOURCE %in% input$energySelect2 & STATE %in% stateSelected & YEAR %in% input$yearSelect2), aes(x = YEAR, y = GENERATION, fill = ENERGY.SOURCE)) +
            geom_bar(position = "fill", stat = "identity") +
            scale_y_continuous(labels = scales::percent) +
            labs(fill = "Sources") +
            xlab("Year") +
            ylab("Percent of total") +
            scale_fill_manual(values = colors)
        } else if("All" %notin% input$yearSelect2) { #Filter by year
            graph <-
            ggplot(subset(data, ENERGY.SOURCE != "Total" & STATE %in% stateSelected & YEAR %in% input$yearSelect2), aes(x = YEAR, y = GENERATION, fill = ENERGY.SOURCE)) +
            geom_bar(position = "fill", stat = "identity") +
            scale_y_continuous(labels = scales::percent) +
            labs(fill = "Sources") +
            xlab("Year") +
            ylab("Percent of total") +
            scale_fill_manual(values = colors)
        }  else if("Total" %notin% input$energySelect2) { #Filter by energy source
            graph <-
            ggplot(subset(data, ENERGY.SOURCE %in% input$energySelect2 & STATE %in% stateSelected), aes(x = YEAR, y = GENERATION, fill = ENERGY.SOURCE)) +
            geom_bar(position = "fill", stat = "identity") +
            scale_y_continuous(labels = scales::percent) +
            labs(fill = "Sources") +
            xlab("Year") +
            ylab("Percent of total") +
            scale_fill_manual(values = colors)
        } else if("US-TOTAL" %notin% stateSelected) { #Filter by state
            graph <-
            ggplot(subset(data, ENERGY.SOURCE != "Total" & STATE %in% stateSelected), aes(x = YEAR, y = GENERATION, fill = ENERGY.SOURCE)) +
            geom_bar(position = "fill", stat = "identity") +
            scale_y_continuous(labels = scales::percent) +
            labs(fill = "Sources") +
            xlab("Year") +
            ylab("Percent of total") +
            scale_fill_manual(values = colors)
        } else { #Default, total for state selected
            graph <-
            ggplot(subset(data, ENERGY.SOURCE != "Total" & STATE %in% stateSelected), aes(x = YEAR, y = GENERATION, fill = ENERGY.SOURCE)) +
            geom_bar(position = "fill", stat = "identity") +
            scale_y_continuous(labels = scales::percent) +
            labs(fill = "Sources") +
            xlab("Year") +
            ylab("Percent of total") +
            scale_fill_manual(values = colors)
        }
        graph
    })
    
    
    #Used to generate line chart of total US production
    output$generatedLine <- renderPlot({
        value <- cat(input$checkGroup)
        
        if("All" %in% input$checkGroup) { #Show all energy sources
            graph <-
            ggplot(usdata, aes(x = YEAR, y = GENERATION, group = ENERGY.SOURCE, color = ENERGY.SOURCE)) + 
            scale_y_continuous(labels = unit_format(unit = "B", scale = 1e-9)) + 
            stat_summary(fun.y = sum, geom = "line") + 
            labs(color = "Energy Sources") + xlab("Year") + ylab("Energy Generated (MWh)") +
            scale_color_manual(values = colors)  
        } else { #Filter by energy source selected
            graph <-
            ggplot(subset(usdata, ENERGY.SOURCE %in% input$checkGroup), aes(x = YEAR, y = GENERATION, group = ENERGY.SOURCE, color = ENERGY.SOURCE)) + 
            scale_y_continuous(labels = unit_format(unit = "B", scale = 1e-9)) + 
            stat_summary(fun.y = sum, geom = "line") + 
            labs(color = "Energy Sources") + xlab("Year") + ylab("Energy Generated (MWh)") +
            scale_color_manual(values = colors)  
         }
            graph
    })
    
    #Used to generate line chart of total US and individual state data
    output$generatedLine1 <- renderPlot({
        value <- cat(input$checkGroup)
        
        #Convert full state name back to abbreviation
        if("Total US" %in% input$stateSelect1) {
            stateSelected <- "US-TOTAL"
        } else if("Washington DC" %in% input$stateSelect1) {
            stateSelected <- "DC"
        } else {
            stateSelected <- state.abb[match(input$stateSelect1,state.name)]
        }
        
        if("All" %notin% input$yearSelect1 && "Total" %notin% input$energySelect1) { #Filter by year and energy source
            graph <-
            ggplot(subset(data, ENERGY.SOURCE %in% input$energySelect1 & STATE %in% stateSelected & YEAR %in% input$yearSelect1), aes(x = YEAR, y = GENERATION, group = ENERGY.SOURCE, color = ENERGY.SOURCE)) +
            scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6)) +
            stat_summary(fun.y = sum, geom = "line") +
            labs(color = "Energy Sources") + xlab("Year") + ylab("Energy Generated (MWh)") +
            scale_color_manual(values = colors)
        } else if("All" %notin% input$yearSelect1) { #Filter by year
            graph <-
            ggplot(subset(data, ENERGY.SOURCE != "Total" & STATE %in% stateSelected & YEAR %in% input$yearSelect1), aes(x = YEAR, y = GENERATION, group = ENERGY.SOURCE, color = ENERGY.SOURCE)) +
            scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6)) +
            stat_summary(fun.y = sum, geom = "line") +
            labs(color = "Energy Sources") + xlab("Year") + ylab("Energy Generated (MWh)") +
            scale_color_manual(values = colors)
        }  else if("Total" %notin% input$energySelect1) { #Filter by energy source
            graph <-
            ggplot(subset(data, ENERGY.SOURCE %in% input$energySelect1 & STATE %in% stateSelected), aes(x = YEAR, y = GENERATION, group = ENERGY.SOURCE, color = ENERGY.SOURCE)) +
            scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6)) +
            stat_summary(fun.y = sum, geom = "line") +
            labs(color = "Energy Sources") + xlab("Year") + ylab("Energy Generated (MWh)") +
            scale_color_manual(values = colors)
        } else if("US-TOTAL" %notin% stateSelected) { #Filter by state
            graph <-
            ggplot(subset(data, ENERGY.SOURCE != "Total" & STATE %in% stateSelected), aes(x = YEAR, y = GENERATION, group = ENERGY.SOURCE, color = ENERGY.SOURCE)) +
            scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6)) +
            stat_summary(fun.y = sum, geom = "line") +
            labs(color = "Energy Sources") + xlab("Year") + ylab("Energy Generated (MWh)") +
            scale_color_manual(values = colors)
        } else { #Default, total for state selected
            graph <-
            ggplot(subset(data, ENERGY.SOURCE != "Total" & STATE %in% stateSelected), aes(x = YEAR, y = GENERATION, group = ENERGY.SOURCE, color = ENERGY.SOURCE)) +
            scale_y_continuous(labels = unit_format(unit = "B", scale = 1e-9)) +
            stat_summary(fun.y = sum, geom = "line") +
            labs(color = "Energy Sources") + xlab("Year") + ylab("Energy Generated (MWh)") +
            scale_color_manual(values = colors)
        }
            graph
    })
    
    #Used to generate line chart of total US and individual state data
    output$generatedLine2 <- renderPlot({
        value <- cat(input$checkGroup)
        
        #Convert full state name back to abbreviation
        if("Total US" %in% input$stateSelect2) {
            stateSelected <- "US-TOTAL"
        } else if("Washington DC" %in% input$stateSelect2) {
            stateSelected <- "DC"
        } else {
            stateSelected <- state.abb[match(input$stateSelect2, state.name)]
        }
        
        if("All" %notin% input$yearSelect2 && "Total" %notin% input$energySelect2) { #Filter by year and energy source
            graph <-
            ggplot(subset(data, ENERGY.SOURCE %in% input$energySelect2 & STATE %in% stateSelected & YEAR %in% input$yearSelect2), aes(x = YEAR, y = GENERATION, group = ENERGY.SOURCE, color = ENERGY.SOURCE)) +
            scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6)) +
            stat_summary(fun.y = sum, geom = "line") +
            labs(color = "Energy Sources") + xlab("Year") + ylab("Energy Generated (MWh)") +
            scale_color_manual(values = colors)
        } else if("All" %notin% input$yearSelect2) { #Filter by year
            graph <-
            ggplot(subset(data, ENERGY.SOURCE != "Total" & STATE %in% stateSelected & YEAR %in% input$yearSelect2), aes(x = YEAR, y = GENERATION, group = ENERGY.SOURCE, color = ENERGY.SOURCE)) +
            scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6)) +
            stat_summary(fun.y = sum, geom = "line") +
            labs(color = "Energy Sources") + xlab("Year") + ylab("Energy Generated (MWh)") +
            scale_color_manual(values = colors)
        }  else if("Total" %notin% input$energySelect2) { #Filter by energy source
            graph <-
            ggplot(subset(data, ENERGY.SOURCE %in% input$energySelect2 & STATE %in% stateSelected), aes(x = YEAR, y = GENERATION, group = ENERGY.SOURCE, color = ENERGY.SOURCE)) +
            scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6)) +
            stat_summary(fun.y = sum, geom = "line") +
            labs(color = "Energy Sources") + xlab("Year") + ylab("Energy Generated (MWh)") +
            scale_color_manual(values = colors)
        } else if("US-TOTAL" %notin% stateSelected) { #Filter by state
            graph <-
            ggplot(subset(data, ENERGY.SOURCE != "Total" & STATE %in% stateSelected), aes(x = YEAR, y = GENERATION, group = ENERGY.SOURCE, color = ENERGY.SOURCE)) +
            scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6)) +
            stat_summary(fun.y = sum, geom = "line") +
            labs(color = "Energy Sources") + xlab("Year") + ylab("Energy Generated (MWh)") +
            scale_color_manual(values = colors)
        } else { #Default, total for state selected
            graph <-
            ggplot(subset(data, ENERGY.SOURCE != "Total" & STATE %in% stateSelected), aes(x = YEAR, y = GENERATION, group = ENERGY.SOURCE, color = ENERGY.SOURCE)) +
            scale_y_continuous(labels = unit_format(unit = "B", scale = 1e-9)) +
            stat_summary(fun.y = sum, geom = "line") +
            labs(color = "Energy Sources") + xlab("Year") + ylab("Energy Generated (MWh)") +
            scale_color_manual(values = colors)
        }
            graph
    })

    
    #Used to generate line chart of total US data by percent
    output$generatedPercentLine <- renderPlot({
        value <- cat(input$checkGroup)
        
        temp <- aggregate(GENERATION ~ ENERGY.SOURCE + YEAR, usdata, sum)
        percent <- transform(temp, PERCENT.OF.TOTAL = ave(GENERATION, YEAR, FUN = function(x) paste0(round(x/sum(x), 4) * 100), "%"))
        percent$PERCENT.OF.TOTAL <- as.numeric(as.character(percent$PERCENT.OF.TOTAL))    
        
        if("All" %in% input$checkGroup) {                                                          
            graph <-
            ggplot(percent, aes(x = YEAR, y = PERCENT.OF.TOTAL, group = ENERGY.SOURCE, color = ENERGY.SOURCE)) + 
            coord_cartesian(ylim = c(0, 100)) +
            stat_summary(fun.y = sum, geom = "line") +
            scale_y_continuous(labels = function(x) paste0(x, "%")) + 
            labs(color = "Energy Sources") + 
            xlab("Year") + 
            ylab("Percent of total") +
            scale_color_manual(values = colors)
        } else {
            graph <- 
            ggplot(subset(percent, ENERGY.SOURCE %in% input$checkGroup), aes(x = YEAR, y = PERCENT.OF.TOTAL, group = ENERGY.SOURCE, color = ENERGY.SOURCE)) + 
            coord_cartesian(ylim = c(0, 100)) +
            stat_summary(fun.y = sum, geom = "line") +
            scale_y_continuous(labels = function(x) paste0(x, "%")) + 
            labs(color = "Energy Sources") + 
            xlab("Year") + 
            ylab("Percent of total") +
            scale_color_manual(values = colors)
         }
         graph
    })
    
    #Used to generate line chart of total US and individual state data by percent
    output$generatedPercentLine1 <- renderPlot({
        value <- cat(input$checkGroup)
        
        #Convert full state name back to abbreviation
        if("Total US" %in% input$stateSelect1) {
            stateSelected <- "US-TOTAL"
        } else if("Washington DC" %in% input$stateSelect1) {
            stateSelected <- "DC"
        } else {
            stateSelected <- state.abb[match(input$stateSelect1,state.name)]
        }
        
        #Calculate percent of energy source production by total US production
        datawithouttotal <- data[data$ENERGY.SOURCE != "Total",]
        temp <- aggregate(GENERATION ~ ENERGY.SOURCE + YEAR + STATE, datawithouttotal, sum)
        percent <- transform(temp, PERCENT.OF.TOTAL = ave(GENERATION, YEAR, FUN = function(x) paste0(round(x/sum(x), 4) * 100), "%"))
        percent$PERCENT.OF.TOTAL <- as.numeric(as.character(percent$PERCENT.OF.TOTAL))

 
 
        if("All" %notin% input$yearSelect1 && "Total" %notin% input$energySelect1) { #Filter by year and energy source
            graph <-
            ggplot(subset(percent, ENERGY.SOURCE %in% input$energySelect1  & STATE %in% stateSelected & YEAR %in% input$yearSelect1), aes(x = YEAR, y = PERCENT.OF.TOTAL, group = ENERGY.SOURCE, color = ENERGY.SOURCE)) +
            coord_cartesian(ylim = c(0, 100)) +
            stat_summary(fun.y = sum, geom = "line") +
            scale_y_continuous(labels = function(x) paste0(x, "%")) +
            labs(color = "Energy Sources") +
            xlab("Year") +
            ylab("Percent of total") +
            scale_color_manual(values = colors)
        } else if("All" %notin% input$yearSelect1) { #Filter by year
            graph <-
            ggplot(subset(percent, ENERGY.SOURCE != "Total"  & STATE %in% stateSelected & YEAR %in% input$yearSelect1), aes(x = YEAR, y = PERCENT.OF.TOTAL, group = ENERGY.SOURCE, color = ENERGY.SOURCE)) +
            coord_cartesian(ylim = c(0, 100)) +
            stat_summary(fun.y = sum, geom = "line") +
            scale_y_continuous(labels = function(x) paste0(x, "%")) +
            labs(color = "Energy Sources") +
            xlab("Year") +
            ylab("Percent of total") +
            scale_color_manual(values = colors)
         }  else if("Total" %notin% input$energySelect1) { #Filter by energy source
             graph <-
             ggplot(subset(percent, ENERGY.SOURCE %in% input$energySelect1 & STATE %in% stateSelected), aes(x = YEAR, y = PERCENT.OF.TOTAL, group = ENERGY.SOURCE, color = ENERGY.SOURCE)) +
             coord_cartesian(ylim = c(0, 100)) +
             stat_summary(fun.y = sum, geom = "line") +
             scale_y_continuous(labels = function(x) paste0(x, "%")) +
             labs(color = "Energy Sources") +
             xlab("Year") +
             ylab("Percent of total") +
             scale_color_manual(values = colors)
         } else if("US-TOTAL" %notin% stateSelected) { #Filter by state
             graph <-
             ggplot(subset(percent, ENERGY.SOURCE != "Total" & STATE %in% stateSelected), aes(x = YEAR, y = PERCENT.OF.TOTAL, group = ENERGY.SOURCE, color = ENERGY.SOURCE)) +
             coord_cartesian(ylim = c(0, 100)) +
             stat_summary(fun.y = sum, geom = "line") +
             scale_y_continuous(labels = function(x) paste0(x, "%")) +
             labs(color = "Energy Sources") +
             xlab("Year") +
             ylab("Percent of total") +
             scale_color_manual(values = colors)
         } else { #Default, total for state selected
             graph <-
             ggplot(percent, aes(x = YEAR, y = PERCENT.OF.TOTAL, group = ENERGY.SOURCE, color = ENERGY.SOURCE)) +
             coord_cartesian(ylim = c(0, 100)) +
             stat_summary(fun.y = sum, geom = "line") +
             scale_y_continuous(labels = function(x) paste0(x, "%")) +
             labs(color = "Energy Sources") +
             xlab("Year") +
             ylab("Percent of total") +
             scale_color_manual(values = colors)
         }
        graph
    })
    
    
    #Used to generate line chart of total US and individual state data by percent
    output$generatedPercentLine2 <- renderPlot({
        value <- cat(input$checkGroup)
        
        #Convert full state name back to abbreviation
        if("Total US" %in% input$stateSelect2) {
            stateSelected <- "US-TOTAL"
        } else if("Washington DC" %in% input$stateSelect2) {
            stateSelected <- "DC"
        } else {
            stateSelected <- state.abb[match(input$stateSelect2, state.name)]
        }
        
        #Calculate percent of energy source production by total US production
        datawithouttotal <- data[data$ENERGY.SOURCE != "Total",]
        temp <- aggregate(GENERATION ~ ENERGY.SOURCE + YEAR + STATE, datawithouttotal, sum)
        percent <- transform(temp, PERCENT.OF.TOTAL = ave(GENERATION, YEAR, FUN = function(x) paste0(round(x/sum(x), 4) * 100), "%"))
        percent$PERCENT.OF.TOTAL <- as.numeric(as.character(percent$PERCENT.OF.TOTAL))

 
 
        if("All" %notin% input$yearSelect2 && "Total" %notin% input$energySelect2) { #Filter by year and energy source
            graph <-
            ggplot(subset(percent, ENERGY.SOURCE %in% input$energySelect2  & STATE %in% stateSelected & YEAR %in% input$yearSelect2), aes(x = YEAR, y = PERCENT.OF.TOTAL, group = ENERGY.SOURCE, color = ENERGY.SOURCE)) +
            coord_cartesian(ylim = c(0, 100)) +
            stat_summary(fun.y = sum, geom = "line") +
            scale_y_continuous(labels = function(x) paste0(x, "%")) +
            labs(color = "Energy Sources") +
            xlab("Year") +
            ylab("Percent of total") +
            scale_color_manual(values = colors)
        } else if("All" %notin% input$yearSelect2) { #Filter by year
            graph <-
            ggplot(subset(percent, ENERGY.SOURCE != "Total"  & STATE %in% stateSelected & YEAR %in% input$yearSelect2), aes(x = YEAR, y = PERCENT.OF.TOTAL, group = ENERGY.SOURCE, color = ENERGY.SOURCE)) +
            coord_cartesian(ylim = c(0, 100)) +
            stat_summary(fun.y = sum, geom = "line") +
            scale_y_continuous(labels = function(x) paste0(x, "%")) +
            labs(color = "Energy Sources") +
            xlab("Year") +
            ylab("Percent of total") +
            scale_color_manual(values = colors)
         }  else if("Total" %notin% input$energySelect2) { #Filter by energy source
             graph <-
             ggplot(subset(percent, ENERGY.SOURCE %in% input$energySelect2 & STATE %in% stateSelected), aes(x = YEAR, y = PERCENT.OF.TOTAL, group = ENERGY.SOURCE, color = ENERGY.SOURCE)) +
             coord_cartesian(ylim = c(0, 100)) +
             stat_summary(fun.y = sum, geom = "line") +
             scale_y_continuous(labels = function(x) paste0(x, "%")) +
             labs(color = "Energy Sources") +
             xlab("Year") +
             ylab("Percent of total") +
             scale_color_manual(values = colors)
         } else if("US-TOTAL" %notin% stateSelected) { #Filter by state
             graph <-
             ggplot(subset(percent, ENERGY.SOURCE != "Total" & STATE %in% stateSelected), aes(x = YEAR, y = PERCENT.OF.TOTAL, group = ENERGY.SOURCE, color = ENERGY.SOURCE)) +
             coord_cartesian(ylim = c(0, 100)) +
             stat_summary(fun.y = sum, geom = "line") +
             scale_y_continuous(labels = function(x) paste0(x, "%")) +
             labs(color = "Energy Sources") +
             xlab("Year") +
             ylab("Percent of total") +
             scale_color_manual(values = colors)
         } else { #Default, total for state selected
             graph <-
             ggplot(percent, aes(x = YEAR, y = PERCENT.OF.TOTAL, group = ENERGY.SOURCE, color = ENERGY.SOURCE)) +
             coord_cartesian(ylim = c(0, 100)) +
             stat_summary(fun.y = sum, geom = "line") +
             scale_y_continuous(labels = function(x) paste0(x, "%")) +
             labs(color = "Energy Sources") +
             xlab("Year") +
             ylab("Percent of total") +
             scale_color_manual(values = colors)
         }
        
        graph
        })
    
    #Generate raw energy data table
    output$generatedTable <- renderDataTable(
        datatable({
            value <- cat(input$checkGroup)
                aggregate(GENERATION ~ ENERGY.SOURCE + YEAR, usdata, FUN = sum)
         }, 
        options = list(paging = FALSE), rownames = FALSE 
        )
    )
                                                          
     #Generate raw energy data table with percent of total
      output$generatedPercentTable <- renderDataTable(
        datatable({
            temp <- aggregate(GENERATION ~ ENERGY.SOURCE + YEAR, usdata, sum)
                transform(temp, PERCENT.OF.TOTAL = ave(GENERATION, YEAR, FUN = function(x) paste0(round(x/sum(x), 4) * 100, "%")))
                                                   
            value <- cat(input$checkGroup)
                transform(temp, PERCENT.OF.TOTAL = ave(GENERATION, YEAR, FUN = function(x) paste0(round(x/sum(x), 4) * 100, "%")))
         }, 
        options = list(paging = FALSE), rownames = FALSE 
        )
    )
}

shinyApp(ui = ui, server = server)
